/* ═══════════════════════════════════════════════════════
   BANQUE DE QUESTIONS — Tu me connais ?
   Structure : QDB[lang][mode][level] = Array de questions
   level : 'normal' | 'fun' | 'hot'
   Chaque question : { q, opts:[{l,e},...] }
   Maximum 4 options par défaut, le bouton + permet d'en ajouter
═══════════════════════════════════════════════════════ */

var QDB = {
  fr: {
    friends: {
      normal: [
        {q:"Ta couleur préférée ?",opts:[{l:"Rouge",e:"🔴"},{l:"Bleu",e:"🔵"},{l:"Vert",e:"🟢"},{l:"Jaune",e:"🟡"}]},
        {q:"Ton genre de musique ?",opts:[{l:"Pop / RnB",e:"🎤"},{l:"Rap / Hip-hop",e:"🎧"},{l:"Rock / Metal",e:"🎸"},{l:"Électro / House",e:"🎛️"}]},
        {q:"Ton vibe du week-end ?",opts:[{l:"Sortir en ville",e:"🌆"},{l:"Canapé et séries",e:"🛋️"},{l:"Sport / Nature",e:"🏃"},{l:"Voir des amis",e:"🤝"}]},
        {q:"Ton repas préféré ?",opts:[{l:"Pizza",e:"🍕"},{l:"Burger",e:"🍔"},{l:"Sushi",e:"🍣"},{l:"Pâtes",e:"🍝"}]},
        {q:"Ton animal préféré ?",opts:[{l:"Chien",e:"🐶"},{l:"Chat",e:"🐱"},{l:"Oiseau",e:"🦜"},{l:"Aucun",e:"🚫"}]},
        {q:"Ta saison préférée ?",opts:[{l:"Été",e:"☀️"},{l:"Printemps",e:"🌸"},{l:"Automne",e:"🍂"},{l:"Hiver",e:"❄️"}]},
        {q:"Comment tu gères la pression ?",opts:[{l:"Cool & calme",e:"😎"},{l:"Un peu stressé",e:"😰"},{l:"Je procrastine",e:"🥱"},{l:"Je fonce",e:"💨"}]},
        {q:"Ton activité physique ?",opts:[{l:"Foot / Basket",e:"⚽"},{l:"Gym / Muscu",e:"🏋️"},{l:"Running / Vélo",e:"🚴"},{l:"Zéro sport",e:"😴"}]},
        {q:"Tes soirées en semaine ?",opts:[{l:"Réseaux sociaux",e:"📱"},{l:"Jeux vidéo",e:"🎮"},{l:"Séries / Films",e:"🎬"},{l:"Lecture / Créa",e:"📚"}]},
        {q:"Ta boisson du quotidien ?",opts:[{l:"Café",e:"☕"},{l:"Thé",e:"🍵"},{l:"Smoothie",e:"🥤"},{l:"Soda",e:"🥤"}]},
        {q:"Ton truc en voyage ?",opts:[{l:"Plage",e:"🏖️"},{l:"Montagne",e:"⛰️"},{l:"Ville & culture",e:"🏛️"},{l:"Aventure",e:"🌿"}]},
        {q:"Tu dors comment ?",opts:[{l:"Couche-tôt",e:"🌅"},{l:"Noctambule",e:"🌙"},{l:"Ça dépend",e:"🤷"},{l:"Roi des siestes",e:"💤"}]},
        {q:"Ton super-pouvoir rêvé ?",opts:[{l:"Voler",e:"🦸"},{l:"Téléportation",e:"⚡"},{l:"Invisibilité",e:"👻"},{l:"Lire les pensées",e:"🧠"}]},
        {q:"En soirée, t'es ?",opts:[{l:"L'âme de la fête",e:"🕺"},{l:"Discret mais là",e:"🤫"},{l:"Je rentre tôt",e:"🚪"},{l:"L'observateur",e:"👀"}]},
        {q:"Ta passion secrète ?",opts:[{l:"Cuisine",e:"👨‍🍳"},{l:"Dessin / Art",e:"🎨"},{l:"Musique / Chant",e:"🎵"},{l:"Gaming",e:"🕹️"}]},
        {q:"Ton film en boucle ?",opts:[{l:"Comédie",e:"😂"},{l:"Action / Thriller",e:"💥"},{l:"Horreur",e:"👻"},{l:"Romance / Drame",e:"💕"}]},
        {q:"Ta ponctualité ?",opts:[{l:"Toujours en avance",e:"⏰"},{l:"À l'heure pile",e:"🎯"},{l:"5 min de retard",e:"😅"},{l:"En retard chrono",e:"🐢"}]},
        {q:"Ce qui t'énerve le plus ?",opts:[{l:"Le bruit",e:"🔊"},{l:"L'impolitesse",e:"😤"},{l:"L'attente",e:"⏳"},{l:"Le désordre",e:"🗑️"}]},
        {q:"Ta façon de gérer un conflit ?",opts:[{l:"J'en parle direct",e:"💬"},{l:"Je laisse passer",e:"🌊"},{l:"J'évite",e:"🙈"},{l:"Plus tard",e:"🕐"}]},
        {q:"Ton objectif de vie ?",opts:[{l:"Liberté",e:"🦋"},{l:"Succès",e:"🏆"},{l:"Bonheur",e:"😊"},{l:"Aventure",e:"🌍"}]},
        {q:"Appli à supprimer en dernier ?",opts:[{l:"Instagram",e:"📸"},{l:"YouTube",e:"▶️"},{l:"Spotify",e:"🎵"},{l:"WhatsApp",e:"💬"}]},
        {q:"Ton rapport à l'argent ?",opts:[{l:"Je dépense vite",e:"💸"},{l:"J'économise",e:"🐷"},{l:"Équilibré",e:"⚖️"},{l:"Au jour le jour",e:"🎲"}]},
        {q:"Ce qui t'aide à te détendre ?",opts:[{l:"Musique",e:"🎧"},{l:"Sport",e:"🏃"},{l:"Nature",e:"🌳"},{l:"Sommeil",e:"😴"}]},
        {q:"Ton ambiance de travail ?",opts:[{l:"Musique fort",e:"🔊"},{l:"Silence total",e:"🤫"},{l:"Bruit de fond",e:"☕"},{l:"N'importe quoi",e:"🤪"}]},
        {q:"Un insecte chez toi, tu ?",opts:[{l:"Je le tue",e:"👟"},{l:"J'attrape et libère",e:"🫙"},{l:"Je hurle",e:"😱"},{l:"J'ignore",e:"😏"}]},
        {q:"Ton rapport aux réseaux ?",opts:[{l:"Accro total",e:"📱"},{l:"Occasionnel",e:"😌"},{l:"Je déteste ça",e:"🙅"},{l:"Un peu seulement",e:"🤙"}]},
        {q:"Quand t'es triste tu ?",opts:[{l:"Je mange",e:"🍫"},{l:"J'appelle un ami",e:"🤗"},{l:"Je m'isole",e:"🛏️"},{l:"Vidéos / Séries",e:"📺"}]},
        {q:"Ton réveil naturel ?",opts:[{l:"Avant 7h",e:"🌄"},{l:"7h-9h",e:"☀️"},{l:"9h-11h",e:"😪"},{l:"Après 11h",e:"💤"}]},
        {q:"Tu attends quelqu'un, tu ?",opts:[{l:"Je scrolle",e:"📱"},{l:"J'observe les gens",e:"👀"},{l:"Je m'impatiente",e:"😠"},{l:"Ça m'est égal",e:"😌"}]},
        {q:"Ta relation à la mode ?",opts:[{l:"Style affirmé",e:"✨"},{l:"Confort avant tout",e:"👕"},{l:"Casual chic",e:"🧥"},{l:"Je m'en fous",e:"🙃"}]},
        {q:"Ton film préféré ?",opts:[{l:"Barbie",e:"👛"},{l:"Donnie Darko",e:"🐰"},{l:"Minions",e:"💛"},{l:"Moi moche et méchant",e:"🦷"}]},
        {q:"Ton jeu vidéo style ?",opts:[{l:"FPS / Action",e:"🔫"},{l:"RPG / Aventure",e:"⚔️"},{l:"Sport / Course",e:"🏎️"},{l:"Je joue pas",e:"🚫"}]},
        {q:"Ta façon d'apprendre ?",opts:[{l:"En regardant",e:"👀"},{l:"En pratiquant",e:"🛠️"},{l:"En lisant",e:"📖"},{l:"En écoutant",e:"🎧"}]},
        {q:"Ton niveau de désordre à la maison ?",opts:[{l:"Ultra rangé",e:"✨"},{l:"Organisé à ma façon",e:"📦"},{l:"Un peu le chaos",e:"🌀"},{l:"Catastrophique",e:"🌪️"}]},
        {q:"Tes vacances idéales ?",opts:[{l:"All-inclusive",e:"🏨"},{l:"Camping sauvage",e:"⛺"},{l:"City trip",e:"🗺️"},{l:"Road trip",e:"🚗"}]},
        {q:"Comment tu prends des décisions ?",opts:[{l:"Au feeling",e:"❤️"},{l:"J'analyse tout",e:"🧠"},{l:"Je demande des avis",e:"🗣️"},{l:"Au hasard presque",e:"🎲"}]},
        {q:"Ton rapport au risque ?",opts:[{l:"J'adore l'adrénaline",e:"⚡"},{l:"Prudemment",e:"🐢"},{l:"Calculé",e:"📊"},{l:"Zéro risque",e:"🛡️"}]},
        {q:"Ta réaction face à une surprise ?",opts:[{l:"Je pleure de joie",e:"🥹"},{l:"Je crie",e:"😱"},{l:"Je souris discret",e:"🙂"},{l:"Je suis choqué",e:"😶"}]},
        {q:"Ton rapport à la ponctualité des autres ?",opts:[{l:"Ça m'énerve vraiment",e:"😤"},{l:"Je l'accepte",e:"🤷"},{l:"Je prévois du marge",e:"⏰"},{l:"Je m'en fiche",e:"😌"}]},
        {q:"Si tu étais un emoji ?",opts:[{l:"😂",e:"😂"},{l:"🔥",e:"🔥"},{l:"😎",e:"😎"},{l:"🥺",e:"🥺"}]}
      ],
      fun: [
        {q:"Ton pire souvenir gênant ?",opts:[{l:"Chute en public",e:"🤕"},{l:"Texto envoyé à la mauvaise personne",e:"📱"},{l:"J'ai dit un truc bizarre",e:"😬"},{l:"Oublié un prénom",e:"😶"}]},
        {q:"Ce que tu fais quand personne regarde ?",opts:[{l:"Je danse seul",e:"🕺"},{l:"Je parle tout seul",e:"🗣️"},{l:"Je mange bizarrement",e:"🍕"},{l:"Je chante faux",e:"🎤"}]},
        {q:"Ton habitude inavouable ?",opts:[{l:"Je suis mes ex sur les réseaux",e:"👀"},{l:"Je googlee des trucs honteux",e:"🔍"},{l:"Je lis les commentaires",e:"📱"},{l:"Je fais semblant de pas avoir vu le message",e:"🙈"}]},
        {q:"Ta plus grande peur illogique ?",opts:[{l:"Les trous (trypophobie)",e:"😱"},{l:"Les mannequins",e:"🪆"},{l:"Les clowns",e:"🤡"},{l:"Les personnages de costumes",e:"🐻"}]},
        {q:"Tu mentirais pour quoi ?",opts:[{l:"Éviter une soirée",e:"🏠"},{l:"Garder mon image",e:"😎"},{l:"Protéger quelqu'un",e:"🛡️"},{l:"Je mens jamais",e:"😇"}]},
        {q:"Ta honte culinaire ?",opts:[{l:"Je mange du Nutella à la cuillère",e:"🍫"},{l:"Je mange froid",e:"❄️"},{l:"Je trempe tout dans la mayo",e:"🥫"},{l:"Je mange des trucs périmés",e:"🧟"}]},
        {q:"Ce que tu fais quand t'es nerveux ?",opts:[{l:"Je tripote mes cheveux",e:"💇"},{l:"Je mange",e:"🍔"},{l:"Je ris sans raison",e:"😂"},{l:"Je parle trop",e:"💬"}]},
        {q:"Ta façon la plus gênante de flirter ?",opts:[{l:"Je deviens muet",e:"😶"},{l:"Je fais le drôle maladroit",e:"🤪"},{l:"J'ignore la personne",e:"🙈"},{l:"Je deviens trop intense",e:"👁️"}]},
        {q:"Ce dont tu es secrètement fier ?",opts:[{l:"Mon talent inutile",e:"🎪"},{l:"Ma playlist parfaite",e:"🎵"},{l:"Ma mémoire des films",e:"🎬"},{l:"Mon sens de l'orientation",e:"🧭"}]},
        {q:"Ton opinion impopulaire ?",opts:[{l:"L'ananas sur la pizza c'est bon",e:"🍕"},{l:"Noel c'est surfait",e:"🎄"},{l:"Les animaux au lit c'est cool",e:"🐶"},{l:"Les vacances c'est surestimé",e:"✈️"}]}
      ],
      hot: [
        {q:"Tu as déjà embrassé quelqu'un de pas prévu ?",opts:[{l:"Oui et j'assume",e:"💋"},{l:"Oui mais chut",e:"🤫"},{l:"Non jamais",e:"😇"},{l:"Ça dépend de votre définition",e:"🤔"}]},
        {q:"Ta limite en soirée ?",opts:[{l:"Je suis sage",e:"😇"},{l:"Quelques verres max",e:"🍺"},{l:"Je teste mes limites",e:"🔥"},{l:"Je m'arrête jamais seul",e:"💀"}]},
        {q:"T'as déjà menti à tes parents pour ?",opts:[{l:"Sortir sans permission",e:"🌙"},{l:"Cacher une relation",e:"💕"},{l:"Les deux",e:"🙈"},{l:"Je leur dis tout",e:"😇"}]},
        {q:"Ton type de crush ?",opts:[{l:"Mystérieux et discret",e:"🌑"},{l:"Solaire et extraverti",e:"☀️"},{l:"Ambitieux et déterminé",e:"🚀"},{l:"Cool et posé",e:"😌"}]},
        {q:"Ton niveau de jalousie ?",opts:[{l:"Zéro jaloux",e:"😇"},{l:"Un peu normal",e:"🙂"},{l:"Assez jaloux honnêtement",e:"😬"},{l:"Limite possessif",e:"🔐"}]},
        {q:"T'as déjà ghosté quelqu'un ?",opts:[{l:"Oui, j'avoue",e:"👻"},{l:"Oui mais j'en ai honte",e:"😞"},{l:"Non jamais",e:"😇"},{l:"J'ai été ghosté moi",e:"🥲"}]},
        {q:"Ta relation au sexe opposé / même sexe ?",opts:[{l:"Plutôt sex-opposé",e:"♀️♂️"},{l:"Plutôt même sexe",e:"🏳️‍🌈"},{l:"Les deux ça dépend",e:"💫"},{l:"Trop personnel",e:"🔒"}]},
        {q:"Ce que tu fais quand t'aimes quelqu'un ?",opts:[{l:"Je suis normal et je dis",e:"💬"},{l:"Je deviens bizarre",e:"🤪"},{l:"J'évite la personne",e:"🙈"},{l:"Je suis en mode espion",e:"🕵️"}]},
        {q:"Ta pire rupture ?",opts:[{l:"Je l'ai pas vu venir",e:"😱"},{l:"C'est moi qui suis parti",e:"🚶"},{l:"Mutuel et clean",e:"🤝"},{l:"J'ai jamais rompu",e:"😇"}]},
        {q:"En couple, tu es plutôt ?",opts:[{l:"Très démonstratif",e:"💕"},{l:"Discret mais intense",e:"🔥"},{l:"Indépendant",e:"🦅"},{l:"Tout dépend de l'autre",e:"🎲"}]}
      ]
    },

    couple: {
      normal: [
        {q:"Ta couleur préférée ?",opts:[{l:"Rouge passion",e:"❤️"},{l:"Bleu calme",e:"💙"},{l:"Vert nature",e:"💚"},{l:"Jaune soleil",e:"💛"}]},
        {q:"Soirée idéale à deux ?",opts:[{l:"Resto ou bar",e:"🥂"},{l:"Film à la maison",e:"🎬"},{l:"Jeux de société",e:"🎲"},{l:"Balade",e:"🌙"}]},
        {q:"Ton langage d'amour ?",opts:[{l:"Mots doux",e:"💬"},{l:"Câlins",e:"🤗"},{l:"Petits gestes",e:"🎁"},{l:"Temps partagé",e:"⏰"}]},
        {q:"Comment tu te lèves ?",opts:[{l:"Souriant et dispo",e:"😊"},{l:"Silencieux, café d'abord",e:"☕"},{l:"Grincheux",e:"😤"},{l:"Variable",e:"🎲"}]},
        {q:"Plat préféré en couple ?",opts:[{l:"Pizza",e:"🍕"},{l:"Raclette / Fondue",e:"🧀"},{l:"Sushi",e:"🍣"},{l:"Barbecue",e:"🍖"}]},
        {q:"Dans le couple tu es ?",opts:[{l:"Celui qui organise",e:"📋"},{l:"Celui qui suit",e:"🤷"},{l:"L'indépendant",e:"🦅"},{l:"Le romantique",e:"🌹"}]},
        {q:"Ton gros défaut en relation ?",opts:[{l:"Je peux être jaloux",e:"😬"},{l:"J'oublie les dates",e:"📅"},{l:"Je m'emporte vite",e:"🔥"},{l:"Manque d'initiative",e:"😴"}]},
        {q:"Voyage de rêve à deux ?",opts:[{l:"Paris",e:"🗼"},{l:"Île tropicale",e:"🏝️"},{l:"Road trip",e:"🚗"},{l:"Japon",e:"🏯"}]},
        {q:"Comment tu gères une dispute ?",opts:[{l:"Direct et verbal",e:"💬"},{l:"Je boude",e:"😒"},{l:"Je fais la paix vite",e:"🕊️"},{l:"Je digère seul",e:"🚶"}]},
        {q:"Valeur la plus importante ?",opts:[{l:"Confiance",e:"🔐"},{l:"Complicité",e:"😄"},{l:"Liberté",e:"🦋"},{l:"Stabilité",e:"⚓"}]},
        {q:"Tu préfères offrir ou recevoir ?",opts:[{l:"Offrir, j'adore",e:"🎁"},{l:"Recevoir, honnêtement",e:"🥹"},{l:"Les deux pareil",e:"⚖️"},{l:"Les gestes comptent plus",e:"💕"}]},
        {q:"Film de couple idéal ?",opts:[{l:"Comédie romantique",e:"😂❤️"},{l:"Film d'action",e:"💥"},{l:"Thriller",e:"😱"},{l:"Documentaire",e:"🎥"}]},
        {q:"Comment tu montres ton stress ?",opts:[{l:"Je me tais",e:"🤐"},{l:"Je parle beaucoup",e:"💬"},{l:"Je mange",e:"🍫"},{l:"Je m'agite",e:"🔄"}]},
        {q:"Ta priorité en ce moment ?",opts:[{l:"Carrière / projets",e:"📈"},{l:"Couple / famille",e:"❤️"},{l:"Ma liberté",e:"🌍"},{l:"Mon bien-être",e:"🧘"}]},
        {q:"Dans 5 ans, tu te vois ?",opts:[{l:"Installé en couple",e:"🏠"},{l:"Voyageant",e:"✈️"},{l:"En pleine carrière",e:"💼"},{l:"Je sais pas encore",e:"🤷"}]},
        {q:"Ton signe astro te correspond ?",opts:[{l:"Oui totalement",e:"⭐"},{l:"Un peu",e:"🙂"},{l:"Pas du tout",e:"❌"},{l:"J'y crois pas",e:"🙄"}]},
        {q:"Température préférée ?",opts:[{l:"Chaud et soleil",e:"☀️"},{l:"Frais et doux",e:"🍃"},{l:"Froid et hivernal",e:"❄️"},{l:"Peu importe",e:"🤷"}]},
        {q:"Rituel du matin en couple ?",opts:[{l:"Câlin au réveil",e:"🤗"},{l:"Café ensemble",e:"☕"},{l:"Chacun son rythme",e:"🚶"},{l:"On se retrouve après",e:"👋"}]},
        {q:"Ce que t'apprécies le plus chez l'autre ?",opts:[{l:"Son humour",e:"😂"},{l:"Sa bienveillance",e:"💛"},{l:"Son ambition",e:"🔥"},{l:"Sa présence",e:"🫂"}]},
        {q:"Ta façon de montrer ton amour ?",opts:[{l:"Mots & messages",e:"💌"},{l:"Actes concrets",e:"🛠️"},{l:"Câlins",e:"🤗"},{l:"Temps de qualité",e:"⏳"}]},
        {q:"Ta dépense coup de cœur ?",opts:[{l:"Vêtements",e:"👗"},{l:"Restos",e:"🍽️"},{l:"Voyages",e:"✈️"},{l:"Gadgets / Techno",e:"📱"}]},
        {q:"Ta plus grande peur en relation ?",opts:[{l:"La trahison",e:"💔"},{l:"La routine",e:"😑"},{l:"L'éloignement",e:"📍"},{l:"La dépendance",e:"🔗"}]},
        {q:"Tu t'endors comment ?",opts:[{l:"En 5 min chrono",e:"💤"},{l:"Long à m'endormir",e:"😩"},{l:"Je lis avant",e:"📖"},{l:"Téléphone jusqu'à dormir",e:"📱"}]},
        {q:"Ton attitude face aux problèmes ?",opts:[{l:"J'affronte direct",e:"💪"},{l:"Je réfléchis d'abord",e:"🧠"},{l:"Je demande de l'aide",e:"🙋"},{l:"J'évite si possible",e:"🙈"}]},
        {q:"Vacances de rêve ?",opts:[{l:"All inclusive plage",e:"🏖️"},{l:"Aventure et trek",e:"🎒"},{l:"Culture & visites",e:"🏛️"},{l:"Cocooning maison",e:"🏠"}]},
        {q:"Repas du soir idéal ?",opts:[{l:"Cuisine maison",e:"👨‍🍳"},{l:"Livraison",e:"🛵"},{l:"Resto",e:"🍽️"},{l:"Rapide",e:"🥪"}]},
        {q:"Quand t'es fatigué tu ?",opts:[{l:"Je deviens irritable",e:"😠"},{l:"Je me ferme",e:"🤐"},{l:"Je le dis clairement",e:"🗣️"},{l:"Je continue quand même",e:"🤯"}]},
        {q:"Ce qui te fait fondre ?",opts:[{l:"L'humour",e:"😂"},{l:"La gentillesse",e:"🥰"},{l:"La confiance en soi",e:"😎"},{l:"L'intelligence",e:"🧠"}]},
        {q:"Ton rythme de vie idéal ?",opts:[{l:"Très actif",e:"🚀"},{l:"Équilibré",e:"⚖️"},{l:"Slow life",e:"🐢"},{l:"Variable",e:"🎢"}]},
        {q:"Tu supportes de dormir comment ?",opts:[{l:"Côte à côte collés",e:"🤗"},{l:"Chacun son côté",e:"↔️"},{l:"Peu importe",e:"🤷"},{l:"Je dors mal avec quelqu'un",e:"😵"}]}
      ],
      fun: [
        {q:"Ton pire habitude bizarre en couple ?",opts:[{l:"Je parle à la nourriture",e:"🍕"},{l:"Je chante des chansons inventées",e:"🎤"},{l:"Je commente tout à voix haute",e:"💬"},{l:"Je nomme les objets",e:"🏷️"}]},
        {q:"Ce qui t'énerve chez l'autre mais tu dis rien ?",opts:[{l:"Sa façon de manger",e:"🍽️"},{l:"Ses habitudes bizarre le matin",e:"☀️"},{l:"Il/elle met trop de temps à répondre",e:"📱"},{l:"Son désordre",e:"🌀"}]},
        {q:"Ton côté possessif honteux ?",opts:[{l:"Je check son téléphone",e:"📱"},{l:"Je me rappelle tout ce qu'il/elle dit",e:"🧠"},{l:"Je suis ses réseaux de trop près",e:"👀"},{l:"Je suis pas possessif(ve)",e:"😇"}]},
        {q:"Ton comportement après une dispute ?",opts:[{l:"Bouder dans mon coin",e:"😤"},{l:"Je cuisine pour me réconcilier",e:"👨‍🍳"},{l:"Je fais comme si rien",e:"🙃"},{l:"J'essaie de faire rire",e:"😂"}]},
        {q:"Ce que tu fais quand l'autre dort ?",opts:[{l:"Je scrolle mon tel",e:"📱"},{l:"Je le regarde dormir haha",e:"👀"},{l:"Je mange en secret",e:"🍫"},{l:"Je dors aussi vite",e:"💤"}]},
        {q:"Ton niveau de dépendance à l'autre ?",opts:[{l:"Très indépendant",e:"🦅"},{l:"J'aime la compagnie",e:"🤝"},{l:"Assez fusionnel",e:"🫂"},{l:"Je peux pas être seul",e:"😅"}]},
        {q:"Ce que tu fais quand tu t'ennuies en couple ?",opts:[{l:"Je propose des activités",e:"🎲"},{l:"Je joue sur mon téléphone",e:"📱"},{l:"Je le/la provoque",e:"😏"},{l:"Je dors",e:"💤"}]},
        {q:"Ta réaction quand l'autre te fait un compliment ?",opts:[{l:"Je rougis",e:"😊"},{l:"Je minimise",e:"🙃"},{l:"J'adore ça",e:"💕"},{l:"Je complimente en retour vite",e:"💬"}]},
        {q:"Ce que tu veux toujours pas avouer ?",opts:[{l:"J'aime ses défauts",e:"💛"},{l:"Parfois il/elle m'énerve",e:"😤"},{l:"Je suis accro à lui/elle",e:"🔗"},{l:"Je suis content(e) quand il/elle sort sans moi",e:"🤫"}]},
        {q:"Ton avis secret sur le couple en public ?",opts:[{l:"J'aime les bisous en public",e:"💋"},{l:"Juste les mains c'est bien",e:"🤝"},{l:"Pas trop en public",e:"🙈"},{l:"Ça dépend de l'humeur",e:"🎲"}]}
      ],
      hot: [
        {q:"Votre fréquence idéale de câlins ?",opts:[{l:"Tout le temps",e:"🤗"},{l:"Quand l'humeur est là",e:"😏"},{l:"Quelques fois par semaine",e:"📅"},{l:"Je préfère pas trop",e:"🙅"}]},
        {q:"Ce qui te rend accro à l'autre ?",opts:[{l:"Son regard",e:"👁️"},{l:"Sa façon de te toucher",e:"🖐️"},{l:"Sa voix",e:"🎤"},{l:"Son odeur",e:"🌸"}]},
        {q:"Ta limite acceptable dans une relation ?",opts:[{l:"Texto avec les ex = problème",e:"📱"},{l:"Sortir seul(e) souvent = ok",e:"🌙"},{l:"Cacher des trucs = non",e:"🚫"},{l:"Je suis assez libre",e:"🦅"}]},
        {q:"T'as déjà eu envie de quelqu'un d'autre en couple ?",opts:[{l:"Jamais vraiment",e:"😇"},{l:"Une attirance sans plus",e:"🙂"},{l:"Oui et j'en ai honte",e:"😳"},{l:"Trop personnel",e:"🔒"}]},
        {q:"La jalousie dans le couple ?",opts:[{l:"C'est une preuve d'amour",e:"❤️"},{l:"C'est un signal d'alarme",e:"⚠️"},{l:"Un peu c'est ok",e:"🤷"},{l:"C'est toxique",e:"☠️"}]},
        {q:"Ce que tu n'as jamais dit mais voulu dire ?",opts:[{l:"Je t'aime vraiment trop",e:"💕"},{l:"Tu m'agaces parfois",e:"😤"},{l:"J'ai besoin de plus d'espace",e:"🌀"},{l:"Je t'ai jamais menti",e:"😇"}]},
        {q:"Ton fantasme de couple ?",opts:[{l:"Voyage romantique surpris",e:"✈️"},{l:"Soirée intime parfaite",e:"🕯️"},{l:"Weekend en amoureux",e:"🏨"},{l:"Je vis déjà mon rêve",e:"😊"}]},
        {q:"Vous avez déjà failli rompre ?",opts:[{l:"Non jamais",e:"😇"},{l:"Une fois mais on a réglé",e:"🤝"},{l:"Plusieurs fois",e:"🎢"},{l:"On est nouveaux ensemble",e:"✨"}]},
        {q:"Ton seuil de tolérance aux défauts de l'autre ?",opts:[{l:"Très tolérant",e:"😌"},{l:"Normal",e:"⚖️"},{l:"Je dis ce qui me dérange",e:"💬"},{l:"Zéro tolérance",e:"🚨"}]},
        {q:"Ce soir vous restez ensemble, c'est ?",opts:[{l:"Film et câlins",e:"🎬🤗"},{l:"Resto romantique",e:"🍽️"},{l:"Jeux et rires",e:"🎲😂"},{l:"Chacun sa soirée",e:"🤷"}]}
      ]
    },

    family: {
      normal: [
        {q:"Ta couleur préférée ?",opts:[{l:"Rouge",e:"🔴"},{l:"Bleu",e:"🔵"},{l:"Vert",e:"🟢"},{l:"Jaune",e:"🟡"}]},
        {q:"Ta saison préférée ?",opts:[{l:"Été",e:"☀️"},{l:"Printemps",e:"🌸"},{l:"Automne",e:"🍂"},{l:"Hiver",e:"❄️"}]},
        {q:"Repas de famille préféré ?",opts:[{l:"Raclette",e:"🧀"},{l:"Barbecue",e:"🔥"},{l:"Pizza maison",e:"🍕"},{l:"Couscous",e:"🍲"}]},
        {q:"Comment t'aides à la maison ?",opts:[{l:"Je cuisine",e:"👨‍🍳"},{l:"Je nettoie",e:"🧹"},{l:"Je fais les courses",e:"🛒"},{l:"Honnêtement, peu",e:"😅"}]},
        {q:"Ton rôle dans la famille ?",opts:[{l:"Le drôle",e:"🤡"},{l:"Le sage",e:"🕊️"},{l:"Le rebelle",e:"🤘"},{l:"Le discret",e:"🤫"}]},
        {q:"Ce que tu gardes de l'enfance ?",opts:[{l:"Un jouet",e:"🪀"},{l:"Une habitude",e:"💭"},{l:"Un souvenir précis",e:"📸"},{l:"Une chanson",e:"🎵"}]},
        {q:"Comment tu gères les disputes en famille ?",opts:[{l:"Je désamorce vite",e:"🕊️"},{l:"Je prends parti",e:"⚔️"},{l:"Je m'éloigne",e:"🚶"},{l:"Je reste neutre",e:"🧘"}]},
        {q:"Ton meilleur plat cuisiné ?",opts:[{l:"Pâtes / Riz",e:"🍝"},{l:"Viande / Poisson",e:"🥩"},{l:"Soupe / Mijoté",e:"🍲"},{l:"Gâteaux",e:"🍰"}]},
        {q:"Comment tu montres ton affection ?",opts:[{l:"Câlins fréquents",e:"🤗"},{l:"Mots & messages",e:"💬"},{l:"Je cuisine / j'aide",e:"🛠️"},{l:"Je suis là quand faut",e:"🫂"}]},
        {q:"Ta valeur familiale principale ?",opts:[{l:"Solidarité",e:"💪"},{l:"Respect",e:"🙏"},{l:"L'humour partagé",e:"😂"},{l:"Liberté de chacun",e:"🦅"}]},
        {q:"Ce que tu aimes faire ensemble ?",opts:[{l:"Films",e:"🎬"},{l:"Jeux de société",e:"🎲"},{l:"Manger ensemble",e:"🍽️"},{l:"Sortir / voyager",e:"🚗"}]},
        {q:"Ton rapport aux réunions de famille ?",opts:[{l:"J'adore",e:"🎉"},{l:"Ça dépend des gens",e:"🙂"},{l:"Un peu trop long",e:"⏰"},{l:"Petits groupes seulement",e:"👥"}]},
        {q:"Ta plus grande fierté ?",opts:[{l:"Mon travail / études",e:"📚"},{l:"Ma famille",e:"❤️"},{l:"Mes valeurs",e:"🌟"},{l:"Mes projets perso",e:"🚀"}]},
        {q:"Comment tu gères le stress ?",opts:[{l:"Sport / marche",e:"🏃"},{l:"Musique",e:"🎧"},{l:"Je parle à quelqu'un",e:"💬"},{l:"Seul dans ma bulle",e:"🫧"}]},
        {q:"Ta tradition préférée ?",opts:[{l:"Repas de fête",e:"🎄"},{l:"Vacances ensemble",e:"✈️"},{l:"Anniversaires",e:"🎂"},{l:"Week-ends",e:"🛋️"}]},
        {q:"Film préféré en famille ?",opts:[{l:"Comédie",e:"😂"},{l:"Animation",e:"🎬"},{l:"Documentaire",e:"📽️"},{l:"Horreur",e:"👻"}]},
        {q:"Tu appelles qui en premier quand ça va pas ?",opts:[{l:"Maman / Papa",e:"👨‍👩‍👧"},{l:"Frère / Sœur",e:"👫"},{l:"Un ami proche",e:"🤝"},{l:"Je gère seul",e:"🧘"}]},
        {q:"Ton truc en vacances ?",opts:[{l:"Mer et soleil",e:"🏖️"},{l:"Montagne",e:"⛰️"},{l:"Ville & culture",e:"🏛️"},{l:"Rester à la maison",e:"🏠"}]},
        {q:"Ta plus belle qualité ?",opts:[{l:"Générosité",e:"🎁"},{l:"Honnêteté",e:"🪞"},{l:"Patience",e:"🧘"},{l:"Humour",e:"😂"}]},
        {q:"Comment tu fêtes les anniversaires ?",opts:[{l:"Grande fête",e:"🎉"},{l:"Repas intime",e:"🕯️"},{l:"Cadeau surprise",e:"🎁"},{l:"Message chaleureux",e:"💌"}]},
        {q:"Ta place à table ?",opts:[{l:"Toujours la même",e:"📍"},{l:"Peu importe",e:"🤷"},{l:"Le bout de table",e:"👑"},{l:"À côté de qui j'aime",e:"❤️"}]},
        {q:"Ton souvenir de vacances en famille ?",opts:[{l:"Road trip",e:"🚗"},{l:"Destination soleil",e:"🌞"},{l:"Camping",e:"⛺"},{l:"Ville inconnue",e:"🗺️"}]},
        {q:"Ce que tu voudrais transmettre ?",opts:[{l:"Des valeurs fortes",e:"🌟"},{l:"La joie de vivre",e:"😄"},{l:"La curiosité",e:"🔍"},{l:"L'amour de la famille",e:"❤️"}]},
        {q:"Ta façon de te réconcilier ?",opts:[{l:"Je fais le premier pas",e:"🤝"},{l:"J'attends que ça passe",e:"⏳"},{l:"J'offre quelque chose",e:"🎁"},{l:"J'en parle directement",e:"💬"}]},
        {q:"Ta vision de la famille idéale ?",opts:[{l:"Proche et soudée",e:"🫂"},{l:"Libre et respectueuse",e:"🦅"},{l:"Joyeuse et spontanée",e:"🎉"},{l:"Stable et bienveillante",e:"🌿"}]}
      ],
      fun: [
        {q:"Ton comportement honteux en famille ?",opts:[{l:"Je fouille dans le frigo la nuit",e:"🌙"},{l:"J'écoute les conversations",e:"👂"},{l:"Je fais semblant de dormir",e:"😴"},{l:"Je mange les restes de tout le monde",e:"🍽️"}]},
        {q:"Ton avis sur les réunions familiales ?",opts:[{l:"J'adore mais je suis épuisé après",e:"🎉😩"},{l:"Je compte les minutes pour partir",e:"⏰"},{l:"Je suis l'instigateur du chaos",e:"😈"},{l:"Je mange et je me tais",e:"🍕🤫"}]},
        {q:"Ce que tu faisais en cachette enfant ?",opts:[{l:"Je lisais sous les couvertures",e:"📖"},{l:"Je regardais la télé la nuit",e:"📺"},{l:"Je mangeais des bonbons cachés",e:"🍬"},{l:"Je faisais semblant d'être malade",e:"🤒"}]},
        {q:"Ta réaction quand quelqu'un débarque à l'improviste ?",opts:[{l:"Je range en urgence",e:"🌪️"},{l:"Je suis ravi",e:"🎉"},{l:"J'ouvre à reculons",e:"😬"},{l:"J'ouvre pas si je peux",e:"🙈"}]},
        {q:"Ce que tu fais à table que tu assumes pas ?",opts:[{l:"Je mange avec les doigts",e:"🖐️"},{l:"Je trempe mon pain dans tout",e:"🍞"},{l:"Je goûte dans les plats des autres",e:"🥄"},{l:"Je finis les assiettes de tout le monde",e:"🍽️"}]},
        {q:"Ton surnom de famille honteux ?",opts:[{l:"Le/la bébé de la famille",e:"👶"},{l:"Le/la rebelle",e:"😈"},{l:"L'introuvable (jamais là)",e:"👻"},{l:"Le mangeur / la mangeuse",e:"🍔"}]},
        {q:"Ta phrase favorite en famille ?",opts:[{l:"'C'est pas moi'",e:"🙅"},{l:"'J'ai faim'",e:"😋"},{l:"'Quand on mange ?'",e:"🍽️"},{l:"'Laissez-moi tranquille'",e:"😤"}]},
        {q:"Ce que tu fais jamais mais promets toujours de faire ?",opts:[{l:"Rappeler des membres de la famille",e:"📞"},{l:"Aider à ranger",e:"🧹"},{l:"Cuisiner",e:"👨‍🍳"},{l:"Arriver à l'heure",e:"⏰"}]},
        {q:"Ta tradition familiale la plus bizarre ?",opts:[{l:"Manger en regardant la télé",e:"📺"},{l:"Chanson spéciale pour les anniversaires",e:"🎵"},{l:"Règles de table étranges",e:"🍽️"},{l:"Ma famille est normale !",e:"😇"}]},
        {q:"Ton comportement en voiture en famille ?",opts:[{l:"Je dors direct",e:"💤"},{l:"Je prends le contrôle de la musique",e:"🎵"},{l:"Je réponds à chaque chose",e:"💬"},{l:"Je regarde mon téléphone",e:"📱"}]}
      ],
      hot: [
        {q:"T'as déjà menti à ta famille pour ?",opts:[{l:"Sortir sans permission",e:"🌙"},{l:"Cacher une relation",e:"💕"},{l:"Protéger quelqu'un",e:"🛡️"},{l:"Je mens jamais à eux",e:"😇"}]},
        {q:"Ce que ta famille sait pas sur toi ?",opts:[{l:"Ma vraie vie sociale",e:"🌆"},{l:"Mes convictions profondes",e:"💭"},{l:"Mon niveau de stress réel",e:"😰"},{l:"Ils savent tout",e:"🔓"}]},
        {q:"Tu as déjà caché une relation à ta famille ?",opts:[{l:"Oui et pour bonne raison",e:"🤫"},{l:"Oui et j'en ai honte",e:"😞"},{l:"Non jamais",e:"😇"},{l:"J'ai essayé mais ils ont deviné",e:"🕵️"}]},
        {q:"Ta relation à l'indépendance de ta famille ?",opts:[{l:"Je veux vivre loin",e:"🌍"},{l:"Proche mais pas trop",e:"🏘️"},{l:"Je veux rester près",e:"🏠"},{l:"Ça dépend des périodes",e:"🎲"}]},
        {q:"Le sujet tabou dans ta famille ?",opts:[{l:"L'argent",e:"💰"},{l:"Les relations amoureuses",e:"💕"},{l:"La politique / religion",e:"🗳️"},{l:"Y'a pas vraiment de tabou",e:"😌"}]},
        {q:"T'as un secret que ta famille ignore ?",opts:[{l:"Oui, assez gros",e:"🤫"},{l:"Oui mais rien de grave",e:"🙂"},{l:"Non ils savent tout",e:"😇"},{l:"Je préfère pas répondre",e:"🔒"}]},
        {q:"Ce que tu n'as jamais dit à un parent ?",opts:[{l:"Merci vraiment",e:"🙏"},{l:"T'as eu raison sur ça",e:"✅"},{l:"J'ai eu peur de te décevoir",e:"😔"},{l:"Je dis tout à mes parents",e:"💬"}]},
        {q:"Ta réaction si tes parents voyaient ton téléphone ?",opts:[{l:"Aucun problème",e:"😇"},{l:"Quelques trucs gênants",e:"😅"},{l:"Je lui arrache des mains",e:"😱"},{l:"Je supprime avant",e:"🗑️"}]},
        {q:"Le comportement que tu as hérité et que tu adores pas ?",opts:[{l:"La procrastination",e:"⏳"},{l:"L'impatience",e:"😤"},{l:"L'inquiétude excessive",e:"😰"},{l:"J'ai pris que les bons côtés",e:"😇"}]},
        {q:"Si tu pouvais changer une chose dans ta famille ?",opts:[{l:"Qu'on se parle plus ouvertement",e:"💬"},{l:"Qu'on se voie plus",e:"🤗"},{l:"Qu'on se dispute moins",e:"🕊️"},{l:"Rien, j'adore comme c'est",e:"❤️"}]}
      ]
    }
  },

  en: {
    friends: {
      normal: [
        {q:"Favorite color?",opts:[{l:"Red",e:"🔴"},{l:"Blue",e:"🔵"},{l:"Green",e:"🟢"},{l:"Yellow",e:"🟡"}]},
        {q:"Go-to music genre?",opts:[{l:"Pop / R&B",e:"🎤"},{l:"Rap / Hip-hop",e:"🎧"},{l:"Rock / Metal",e:"🎸"},{l:"Electronic",e:"🎛️"}]},
        {q:"Weekend vibe?",opts:[{l:"Out in the city",e:"🌆"},{l:"Couch & series",e:"🛋️"},{l:"Sports / Nature",e:"🏃"},{l:"Hang with friends",e:"🤝"}]},
        {q:"Favorite meal?",opts:[{l:"Pizza",e:"🍕"},{l:"Burger",e:"🍔"},{l:"Sushi",e:"🍣"},{l:"Pasta",e:"🍝"}]},
        {q:"Favorite animal?",opts:[{l:"Dog",e:"🐶"},{l:"Cat",e:"🐱"},{l:"Bird",e:"🦜"},{l:"None",e:"🚫"}]},
        {q:"Favorite season?",opts:[{l:"Summer",e:"☀️"},{l:"Spring",e:"🌸"},{l:"Autumn",e:"🍂"},{l:"Winter",e:"❄️"}]},
        {q:"How do you handle pressure?",opts:[{l:"Cool & calm",e:"😎"},{l:"A bit stressed",e:"😰"},{l:"I procrastinate",e:"🥱"},{l:"I charge ahead",e:"💨"}]},
        {q:"Physical activity?",opts:[{l:"Soccer / Basketball",e:"⚽"},{l:"Gym / Lifting",e:"🏋️"},{l:"Running / Cycling",e:"🚴"},{l:"None",e:"😴"}]},
        {q:"Weeknight habits?",opts:[{l:"Social media",e:"📱"},{l:"Video games",e:"🎮"},{l:"Shows / Movies",e:"🎬"},{l:"Reading / Creativity",e:"📚"}]},
        {q:"Daily drink of choice?",opts:[{l:"Coffee",e:"☕"},{l:"Tea",e:"🍵"},{l:"Smoothie",e:"🥤"},{l:"Soda",e:"🥤"}]},
        {q:"Your travel style?",opts:[{l:"Beach",e:"🏖️"},{l:"Mountains",e:"⛰️"},{l:"City & culture",e:"🏛️"},{l:"Adventure",e:"🌿"}]},
        {q:"Sleep style?",opts:[{l:"Early bird",e:"🌅"},{l:"Night owl",e:"🌙"},{l:"Depends",e:"🤷"},{l:"Nap king/queen",e:"💤"}]},
        {q:"Dream superpower?",opts:[{l:"Flying",e:"🦸"},{l:"Teleportation",e:"⚡"},{l:"Invisibility",e:"👻"},{l:"Mind reading",e:"🧠"}]},
        {q:"You at a party?",opts:[{l:"Life of the party",e:"🕺"},{l:"Quiet but present",e:"🤫"},{l:"I leave early",e:"🚪"},{l:"The observer",e:"👀"}]},
        {q:"Secret passion?",opts:[{l:"Cooking",e:"👨‍🍳"},{l:"Drawing / Art",e:"🎨"},{l:"Music / Singing",e:"🎵"},{l:"Gaming",e:"🕹️"}]},
        {q:"Movie genre on repeat?",opts:[{l:"Comedy",e:"😂"},{l:"Action / Thriller",e:"💥"},{l:"Horror",e:"👻"},{l:"Romance / Drama",e:"💕"}]},
        {q:"Punctuality level?",opts:[{l:"Always early",e:"⏰"},{l:"Right on time",e:"🎯"},{l:"5 min late",e:"😅"},{l:"Chronically late",e:"🐢"}]},
        {q:"What annoys you most?",opts:[{l:"Noise",e:"🔊"},{l:"Rudeness",e:"😤"},{l:"Waiting",e:"⏳"},{l:"Mess",e:"🗑️"}]},
        {q:"Your conflict style?",opts:[{l:"I address it directly",e:"💬"},{l:"I let it go",e:"🌊"},{l:"I avoid it",e:"🙈"},{l:"Later",e:"🕐"}]},
        {q:"Your life goal?",opts:[{l:"Freedom",e:"🦋"},{l:"Success",e:"🏆"},{l:"Happiness",e:"😊"},{l:"Adventure",e:"🌍"}]},
        {q:"Last app you'd delete?",opts:[{l:"Instagram",e:"📸"},{l:"YouTube",e:"▶️"},{l:"Spotify",e:"🎵"},{l:"WhatsApp",e:"💬"}]},
        {q:"Relationship with money?",opts:[{l:"I spend fast",e:"💸"},{l:"I save everything",e:"🐷"},{l:"Balanced",e:"⚖️"},{l:"Day by day",e:"🎲"}]},
        {q:"What helps you unwind?",opts:[{l:"Music",e:"🎧"},{l:"Sports",e:"🏃"},{l:"Nature",e:"🌳"},{l:"Sleep",e:"😴"}]},
        {q:"Work environment?",opts:[{l:"Loud music",e:"🔊"},{l:"Total silence",e:"🤫"},{l:"Café background",e:"☕"},{l:"Anything goes",e:"🤪"}]},
        {q:"You find a bug at home, you:",opts:[{l:"Kill it",e:"👟"},{l:"Catch & release",e:"🫙"},{l:"Scream",e:"😱"},{l:"Ignore it",e:"😏"}]},
        {q:"Social media use?",opts:[{l:"Totally addicted",e:"📱"},{l:"Occasional",e:"😌"},{l:"I hate it",e:"🙅"},{l:"Light user",e:"🤙"}]},
        {q:"When sad, you:",opts:[{l:"Eat",e:"🍫"},{l:"Call a friend",e:"🤗"},{l:"Isolate",e:"🛏️"},{l:"Watch videos",e:"📺"}]},
        {q:"Natural wake-up time?",opts:[{l:"Before 7am",e:"🌄"},{l:"7–9am",e:"☀️"},{l:"9–11am",e:"😪"},{l:"After 11am",e:"💤"}]},
        {q:"Waiting for someone, you:",opts:[{l:"Scroll my phone",e:"📱"},{l:"People-watch",e:"👀"},{l:"Get impatient",e:"😠"},{l:"Don't mind",e:"😌"}]},
        {q:"Relationship with fashion?",opts:[{l:"Signature style",e:"✨"},{l:"Comfort first",e:"👕"},{l:"Casual chic",e:"🧥"},{l:"Totally indifferent",e:"🙃"}]}
      ],
      fun: [
        {q:"What do you do when no one's watching?",opts:[{l:"Dance alone",e:"🕺"},{l:"Talk to myself",e:"🗣️"},{l:"Eat weirdly",e:"🍕"},{l:"Sing off-key",e:"🎤"}]},
        {q:"Your most embarrassing habit?",opts:[{l:"I stalk exes online",e:"👀"},{l:"I Google shameful stuff",e:"🔍"},{l:"I read all the comments",e:"📱"},{l:"I pretend not to see messages",e:"🙈"}]},
        {q:"Your most illogical fear?",opts:[{l:"Holes (trypophobia)",e:"😱"},{l:"Mannequins",e:"🪆"},{l:"Clowns",e:"🤡"},{l:"Costumed characters",e:"🐻"}]},
        {q:"You would lie to:",opts:[{l:"Avoid a party",e:"🏠"},{l:"Protect your image",e:"😎"},{l:"Protect someone",e:"🛡️"},{l:"I never lie",e:"😇"}]},
        {q:"Your food shame?",opts:[{l:"I eat Nutella with a spoon",e:"🍫"},{l:"I eat everything cold",e:"❄️"},{l:"I dip everything in mayo",e:"🥫"},{l:"I eat expired stuff",e:"🧟"}]},
        {q:"What you do when nervous?",opts:[{l:"I fidget with my hair",e:"💇"},{l:"I eat",e:"🍔"},{l:"I laugh for no reason",e:"😂"},{l:"I talk too much",e:"💬"}]},
        {q:"Your cringiest flirting style?",opts:[{l:"I go silent",e:"😶"},{l:"I try too hard to be funny",e:"🤪"},{l:"I ignore the person",e:"🙈"},{l:"I get way too intense",e:"👁️"}]},
        {q:"What you're secretly proud of?",opts:[{l:"My useless talent",e:"🎪"},{l:"My perfect playlist",e:"🎵"},{l:"My movie trivia memory",e:"🎬"},{l:"My sense of direction",e:"🧭"}]},
        {q:"Your unpopular opinion?",opts:[{l:"Pineapple on pizza is good",e:"🍕"},{l:"Christmas is overrated",e:"🎄"},{l:"Pets in the bed is fine",e:"🐶"},{l:"Vacations are overrated",e:"✈️"}]},
        {q:"Your worst embarrassing memory?",opts:[{l:"Fell in public",e:"🤕"},{l:"Texted the wrong person",e:"📱"},{l:"Said something weird",e:"😬"},{l:"Forgot someone's name",e:"😶"}]}
      ],
      hot: [
        {q:"Have you ever kissed someone unexpectedly?",opts:[{l:"Yes and I own it",e:"💋"},{l:"Yes but shhhh",e:"🤫"},{l:"Never",e:"😇"},{l:"Depends on your definition",e:"🤔"}]},
        {q:"Your limit at a party?",opts:[{l:"I'm well-behaved",e:"😇"},{l:"A few drinks max",e:"🍺"},{l:"I push limits",e:"🔥"},{l:"I never stop myself",e:"💀"}]},
        {q:"You've lied to your parents to:",opts:[{l:"Go out without permission",e:"🌙"},{l:"Hide a relationship",e:"💕"},{l:"Both",e:"🙈"},{l:"I tell them everything",e:"😇"}]},
        {q:"Your type of crush?",opts:[{l:"Mysterious & quiet",e:"🌑"},{l:"Sunny & outgoing",e:"☀️"},{l:"Ambitious",e:"🚀"},{l:"Cool & laid-back",e:"😌"}]},
        {q:"Your jealousy level?",opts:[{l:"Zero jealous",e:"😇"},{l:"A bit, normal",e:"🙂"},{l:"Pretty jealous honestly",e:"😬"},{l:"Borderline possessive",e:"🔐"}]},
        {q:"Have you ever ghosted someone?",opts:[{l:"Yes, I admit it",e:"👻"},{l:"Yes and I'm not proud",e:"😞"},{l:"Never",e:"😇"},{l:"I was the one ghosted",e:"🥲"}]},
        {q:"Your attraction?",opts:[{l:"Mostly opposite sex",e:"♀️♂️"},{l:"Mostly same sex",e:"🏳️‍🌈"},{l:"Both, depends",e:"💫"},{l:"Too personal",e:"🔒"}]},
        {q:"When you like someone, you:",opts:[{l:"Just say it normally",e:"💬"},{l:"Get weird",e:"🤪"},{l:"Avoid them",e:"🙈"},{l:"Go into spy mode",e:"🕵️"}]},
        {q:"Your worst breakup?",opts:[{l:"Didn't see it coming",e:"😱"},{l:"I was the one who left",e:"🚶"},{l:"Mutual and clean",e:"🤝"},{l:"Never broken up",e:"😇"}]},
        {q:"In a relationship you're:",opts:[{l:"Very affectionate",e:"💕"},{l:"Quiet but intense",e:"🔥"},{l:"Independent",e:"🦅"},{l:"Depends on the other person",e:"🎲"}]}
      ]
    },
    couple: {
      normal: [
        {q:"Your favorite color?",opts:[{l:"Passionate red",e:"❤️"},{l:"Calm blue",e:"💙"},{l:"Nature green",e:"💚"},{l:"Sunny yellow",e:"💛"}]},
        {q:"Ideal evening together?",opts:[{l:"Restaurant / bar",e:"🥂"},{l:"Movie at home",e:"🎬"},{l:"Board games",e:"🎲"},{l:"Walk / stroll",e:"🌙"}]},
        {q:"Your love language?",opts:[{l:"Words of affirmation",e:"💬"},{l:"Physical touch",e:"🤗"},{l:"Acts of service",e:"🎁"},{l:"Quality time",e:"⏰"}]},
        {q:"How are you in the morning?",opts:[{l:"Cheerful & ready",e:"😊"},{l:"Quiet, coffee first",e:"☕"},{l:"Grumpy",e:"😤"},{l:"Varies",e:"🎲"}]},
        {q:"Favorite shared meal?",opts:[{l:"Pizza",e:"🍕"},{l:"Cheese fondue",e:"🧀"},{l:"Sushi",e:"🍣"},{l:"BBQ",e:"🍖"}]},
        {q:"In the relationship you're:",opts:[{l:"The organizer",e:"📋"},{l:"The follower",e:"🤷"},{l:"The independent one",e:"🦅"},{l:"The romantic",e:"🌹"}]},
        {q:"Your biggest relationship flaw?",opts:[{l:"I can get jealous",e:"😬"},{l:"I forget dates",e:"📅"},{l:"I flare up fast",e:"🔥"},{l:"Lack of initiative",e:"😴"}]},
        {q:"Dream trip for two?",opts:[{l:"Paris",e:"🗼"},{l:"Tropical island",e:"🏝️"},{l:"Road trip",e:"🚗"},{l:"Japan",e:"🏯"}]},
        {q:"How do you handle a fight?",opts:[{l:"Direct & verbal",e:"💬"},{l:"I sulk",e:"😒"},{l:"I make peace fast",e:"🕊️"},{l:"I digest alone",e:"🚶"}]},
        {q:"Most important relationship value?",opts:[{l:"Trust",e:"🔐"},{l:"Complicity",e:"😄"},{l:"Freedom",e:"🦋"},{l:"Stability",e:"⚓"}]},
        {q:"Prefer giving or receiving?",opts:[{l:"Giving — I love it",e:"🎁"},{l:"Receiving, honestly",e:"🥹"},{l:"Both equally",e:"⚖️"},{l:"Gestures matter more",e:"💕"}]},
        {q:"Couple movie night?",opts:[{l:"Romantic comedy",e:"😂❤️"},{l:"Action movie",e:"💥"},{l:"Thriller",e:"😱"},{l:"Documentary",e:"🎥"}]},
        {q:"How do you show stress?",opts:[{l:"I go quiet",e:"🤐"},{l:"I talk a lot",e:"💬"},{l:"I eat",e:"🍫"},{l:"I fidget",e:"🔄"}]},
        {q:"Biggest priority right now?",opts:[{l:"Career / projects",e:"📈"},{l:"Couple / family",e:"❤️"},{l:"My freedom",e:"🌍"},{l:"My well-being",e:"🧘"}]},
        {q:"In 5 years you see yourself:",opts:[{l:"Settled as a couple",e:"🏠"},{l:"Traveling",e:"✈️"},{l:"Deep in career",e:"💼"},{l:"Not sure yet",e:"🤷"}]},
        {q:"Does your star sign fit?",opts:[{l:"Totally yes",e:"⭐"},{l:"Somewhat",e:"🙂"},{l:"Not at all",e:"❌"},{l:"I don't believe in it",e:"🙄"}]},
        {q:"Preferred temperature?",opts:[{l:"Warm & sunny",e:"☀️"},{l:"Cool & mild",e:"🍃"},{l:"Cold & wintry",e:"❄️"},{l:"Doesn't matter",e:"🤷"}]},
        {q:"Morning ritual as a couple?",opts:[{l:"Morning cuddle",e:"🤗"},{l:"Coffee together",e:"☕"},{l:"Each at own pace",e:"🚶"},{l:"Meet after",e:"👋"}]},
        {q:"What you value most in them?",opts:[{l:"Their humor",e:"😂"},{l:"Their kindness",e:"💛"},{l:"Their ambition",e:"🔥"},{l:"Their presence",e:"🫂"}]},
        {q:"How do you show love?",opts:[{l:"Words & messages",e:"💌"},{l:"Concrete acts",e:"🛠️"},{l:"Hugs & touch",e:"🤗"},{l:"Quality time",e:"⏳"}]},
        {q:"Your impulse purchase?",opts:[{l:"Clothes",e:"👗"},{l:"Restaurants",e:"🍽️"},{l:"Travel",e:"✈️"},{l:"Gadgets / Tech",e:"📱"}]},
        {q:"Biggest fear in a relationship?",opts:[{l:"Betrayal",e:"💔"},{l:"Routine",e:"😑"},{l:"Growing apart",e:"📍"},{l:"Dependency",e:"🔗"}]},
        {q:"How do you fall asleep?",opts:[{l:"Out in 5 min",e:"💤"},{l:"Takes forever",e:"😩"},{l:"I read first",e:"📖"},{l:"Phone until I doze off",e:"📱"}]},
        {q:"Approach to problems?",opts:[{l:"Face them head-on",e:"💪"},{l:"Think first",e:"🧠"},{l:"Ask for help",e:"🙋"},{l:"Avoid if possible",e:"🙈"}]},
        {q:"Dream vacation?",opts:[{l:"All-inclusive beach",e:"🏖️"},{l:"Adventure trek",e:"🎒"},{l:"Cultural discovery",e:"🏛️"},{l:"Cozy home",e:"🏠"}]}
      ],
      fun:[
        {q:"Your weirdest couple habit?",opts:[{l:"I talk to food",e:"🍕"},{l:"I make up songs",e:"🎤"},{l:"I narrate everything",e:"💬"},{l:"I name objects",e:"🏷️"}]},
        {q:"What annoys you about them but you say nothing?",opts:[{l:"How they eat",e:"🍽️"},{l:"Their morning habits",e:"☀️"},{l:"Takes too long to reply",e:"📱"},{l:"Their mess",e:"🌀"}]},
        {q:"Your honest behavior after a fight?",opts:[{l:"I sulk alone",e:"😤"},{l:"I cook to make up",e:"👨‍🍳"},{l:"I act like nothing happened",e:"🙃"},{l:"I try to make them laugh",e:"😂"}]},
        {q:"What you do when they're asleep?",opts:[{l:"Scroll my phone",e:"📱"},{l:"Watch them sleep lol",e:"👀"},{l:"Secret snack",e:"🍫"},{l:"Fall asleep immediately",e:"💤"}]},
        {q:"Your dependency level?",opts:[{l:"Very independent",e:"🦅"},{l:"I enjoy company",e:"🤝"},{l:"Pretty attached",e:"🫂"},{l:"I can't be alone",e:"😅"}]},
        {q:"When bored as a couple you:",opts:[{l:"Suggest activities",e:"🎲"},{l:"Go on my phone",e:"📱"},{l:"Tease them",e:"😏"},{l:"Sleep",e:"💤"}]},
        {q:"When they compliment you, you:",opts:[{l:"Blush",e:"😊"},{l:"Downplay it",e:"🙃"},{l:"Love it",e:"💕"},{l:"Quickly compliment back",e:"💬"}]},
        {q:"Something you won't admit?",opts:[{l:"I love their flaws",e:"💛"},{l:"Sometimes they annoy me",e:"😤"},{l:"I'm addicted to them",e:"🔗"},{l:"I'm happy when they're out",e:"🤫"}]},
        {q:"Your secret view on PDA?",opts:[{l:"I love kisses in public",e:"💋"},{l:"Just holding hands is fine",e:"🤝"},{l:"Not too much in public",e:"🙈"},{l:"Depends on mood",e:"🎲"}]},
        {q:"Your possessive honest side?",opts:[{l:"I check their phone",e:"📱"},{l:"I remember everything they say",e:"🧠"},{l:"I track their socials",e:"👀"},{l:"I'm not possessive",e:"😇"}]}
      ],
      hot:[
        {q:"Your ideal cuddle frequency?",opts:[{l:"All the time",e:"🤗"},{l:"When the mood strikes",e:"😏"},{l:"Few times a week",e:"📅"},{l:"I prefer not too much",e:"🙅"}]},
        {q:"What makes you addicted to them?",opts:[{l:"Their eyes",e:"👁️"},{l:"Their touch",e:"🖐️"},{l:"Their voice",e:"🎤"},{l:"Their scent",e:"🌸"}]},
        {q:"Your relationship dealbreaker?",opts:[{l:"Texting exes = problem",e:"📱"},{l:"Going out alone often = fine",e:"🌙"},{l:"Hiding things = no",e:"🚫"},{l:"I'm pretty flexible",e:"🦅"}]},
        {q:"Have you ever been attracted to someone else while in a relationship?",opts:[{l:"Never really",e:"😇"},{l:"A passing attraction",e:"🙂"},{l:"Yes and I feel guilty",e:"😳"},{l:"Too personal",e:"🔒"}]},
        {q:"Jealousy in a relationship?",opts:[{l:"It's proof of love",e:"❤️"},{l:"It's a warning sign",e:"⚠️"},{l:"A little is okay",e:"🤷"},{l:"It's toxic",e:"☠️"}]},
        {q:"Something you've wanted to say but haven't?",opts:[{l:"I love you way too much",e:"💕"},{l:"You annoy me sometimes",e:"😤"},{l:"I need more space",e:"🌀"},{l:"I've never lied to you",e:"😇"}]},
        {q:"Your couple fantasy?",opts:[{l:"Surprise romantic trip",e:"✈️"},{l:"Perfect intimate evening",e:"🕯️"},{l:"Lovers' weekend",e:"🏨"},{l:"I'm already living my dream",e:"😊"}]},
        {q:"Have you ever almost broken up?",opts:[{l:"Never",e:"😇"},{l:"Once but we fixed it",e:"🤝"},{l:"Several times",e:"🎢"},{l:"We're new together",e:"✨"}]},
        {q:"Your flaw tolerance with them?",opts:[{l:"Very tolerant",e:"😌"},{l:"Normal",e:"⚖️"},{l:"I speak up",e:"💬"},{l:"Zero tolerance",e:"🚨"}]},
        {q:"Tonight together, it's:",opts:[{l:"Movie & cuddles",e:"🎬🤗"},{l:"Romantic dinner",e:"🍽️"},{l:"Games & laughs",e:"🎲😂"},{l:"Each does their own thing",e:"🤷"}]}
      ]
    },
    family:{
      normal:[
        {q:"Favorite color?",opts:[{l:"Red",e:"🔴"},{l:"Blue",e:"🔵"},{l:"Green",e:"🟢"},{l:"Yellow",e:"🟡"}]},
        {q:"Favorite season?",opts:[{l:"Summer",e:"☀️"},{l:"Spring",e:"🌸"},{l:"Autumn",e:"🍂"},{l:"Winter",e:"❄️"}]},
        {q:"Favorite family meal?",opts:[{l:"Cheese fondue",e:"🧀"},{l:"BBQ",e:"🔥"},{l:"Homemade pizza",e:"🍕"},{l:"Stew / tagine",e:"🍲"}]},
        {q:"How do you help at home?",opts:[{l:"I cook",e:"👨‍🍳"},{l:"I clean",e:"🧹"},{l:"I do the shopping",e:"🛒"},{l:"Honestly, not much",e:"😅"}]},
        {q:"Your role in the family?",opts:[{l:"The funny one",e:"🤡"},{l:"The wise one",e:"🕊️"},{l:"The rebel",e:"🤘"},{l:"The quiet one",e:"🤫"}]},
        {q:"What you keep from childhood?",opts:[{l:"A toy / object",e:"🪀"},{l:"A habit",e:"💭"},{l:"A specific memory",e:"📸"},{l:"A song",e:"🎵"}]},
        {q:"Your approach to family arguments?",opts:[{l:"I defuse quickly",e:"🕊️"},{l:"I take sides",e:"⚔️"},{l:"I step away",e:"🚶"},{l:"I stay neutral",e:"🧘"}]},
        {q:"Dish you cook best?",opts:[{l:"Pasta / Rice",e:"🍝"},{l:"Meat / Fish",e:"🥩"},{l:"Soup / Stew",e:"🍲"},{l:"Cakes / Desserts",e:"🍰"}]},
        {q:"How do you show family affection?",opts:[{l:"Frequent hugs",e:"🤗"},{l:"Words & messages",e:"💬"},{l:"I cook / help",e:"🛠️"},{l:"I'm there when needed",e:"🫂"}]},
        {q:"Your main family value?",opts:[{l:"Solidarity",e:"💪"},{l:"Respect",e:"🙏"},{l:"Shared humor",e:"😂"},{l:"Everyone's freedom",e:"🦅"}]},
        {q:"Favorite family activity?",opts:[{l:"Movies",e:"🎬"},{l:"Board games",e:"🎲"},{l:"Eating together",e:"🍽️"},{l:"Outings / travel",e:"🚗"}]},
        {q:"Biggest personal pride?",opts:[{l:"My work / studies",e:"📚"},{l:"My family",e:"❤️"},{l:"My values",e:"🌟"},{l:"My personal projects",e:"🚀"}]},
        {q:"How do you handle stress?",opts:[{l:"Sports / walking",e:"🏃"},{l:"Music",e:"🎧"},{l:"Talk to someone",e:"💬"},{l:"Alone in my bubble",e:"🫧"}]},
        {q:"Favorite family tradition?",opts:[{l:"Holiday meals",e:"🎄"},{l:"Vacations together",e:"✈️"},{l:"Birthdays",e:"🎂"},{l:"Relaxing weekends",e:"🛋️"}]},
        {q:"Favorite family movie genre?",opts:[{l:"Comedy",e:"😂"},{l:"Animation",e:"🎬"},{l:"Documentary",e:"📽️"},{l:"Horror",e:"👻"}]}
      ],
      fun:[
        {q:"Your shameful family behavior?",opts:[{l:"Midnight fridge raids",e:"🌙"},{l:"I eavesdrop",e:"👂"},{l:"I pretend to be asleep",e:"😴"},{l:"I finish everyone's leftovers",e:"🍽️"}]},
        {q:"Your take on family gatherings?",opts:[{l:"Love it but exhausted after",e:"🎉😩"},{l:"Counting minutes to leave",e:"⏰"},{l:"I'm the chaos instigator",e:"😈"},{l:"I eat and stay quiet",e:"🍕🤫"}]},
        {q:"What you did in secret as a kid?",opts:[{l:"Read under the covers",e:"📖"},{l:"Watched TV at night",e:"📺"},{l:"Ate hidden candy",e:"🍬"},{l:"Faked being sick",e:"🤒"}]},
        {q:"Someone shows up unannounced, you:",opts:[{l:"Emergency tidy-up",e:"🌪️"},{l:"I'm delighted",e:"🎉"},{l:"Open the door reluctantly",e:"😬"},{l:"Pretend I'm not home",e:"🙈"}]},
        {q:"Your table habit you don't own up to?",opts:[{l:"I eat with my fingers",e:"🖐️"},{l:"I dip bread in everything",e:"🍞"},{l:"I taste from others' plates",e:"🥄"},{l:"I finish everyone's portions",e:"🍽️"}]},
        {q:"Your family nickname (shameful)?",opts:[{l:"The baby of the family",e:"👶"},{l:"The rebel",e:"😈"},{l:"The invisible one",e:"👻"},{l:"The eater",e:"🍔"}]},
        {q:"Your go-to family line?",opts:[{l:"'It wasn't me'",e:"🙅"},{l:"'I'm hungry'",e:"😋"},{l:"'When do we eat?'",e:"🍽️"},{l:"'Leave me alone'",e:"😤"}]},
        {q:"What you promise but never do?",opts:[{l:"Call relatives back",e:"📞"},{l:"Help tidy up",e:"🧹"},{l:"Cook",e:"👨‍🍳"},{l:"Arrive on time",e:"⏰"}]},
        {q:"Your strangest family tradition?",opts:[{l:"Eating while watching TV",e:"📺"},{l:"Special birthday song",e:"🎵"},{l:"Strange table rules",e:"🍽️"},{l:"My family is totally normal!",e:"😇"}]},
        {q:"Your behavior in the car on family trips?",opts:[{l:"Fall asleep immediately",e:"💤"},{l:"Take control of music",e:"🎵"},{l:"Comment on everything",e:"💬"},{l:"Stare at my phone",e:"📱"}]}
      ],
      hot:[
        {q:"You've lied to your family to:",opts:[{l:"Go out without permission",e:"🌙"},{l:"Hide a relationship",e:"💕"},{l:"Protect someone",e:"🛡️"},{l:"I never lie to them",e:"😇"}]},
        {q:"What your family doesn't know about you?",opts:[{l:"My actual social life",e:"🌆"},{l:"My real beliefs",e:"💭"},{l:"My actual stress level",e:"😰"},{l:"They know everything",e:"🔓"}]},
        {q:"Have you hidden a relationship from family?",opts:[{l:"Yes, for good reason",e:"🤫"},{l:"Yes and not proud",e:"😞"},{l:"Never",e:"😇"},{l:"Tried but they guessed",e:"🕵️"}]},
        {q:"Your relationship with family independence?",opts:[{l:"I want to live far",e:"🌍"},{l:"Close but not too much",e:"🏘️"},{l:"Stay nearby",e:"🏠"},{l:"Depends on the period",e:"🎲"}]},
        {q:"Your family's taboo topic?",opts:[{l:"Money",e:"💰"},{l:"Romantic relationships",e:"💕"},{l:"Politics / Religion",e:"🗳️"},{l:"No real taboo",e:"😌"}]},
        {q:"You have a secret your family ignores?",opts:[{l:"Yes, fairly big",e:"🤫"},{l:"Yes but nothing serious",e:"🙂"},{l:"No, they know all",e:"😇"},{l:"I'd rather not say",e:"🔒"}]},
        {q:"Something you've never said to a parent?",opts:[{l:"Thank you, truly",e:"🙏"},{l:"You were right about that",e:"✅"},{l:"I was scared to disappoint you",e:"😔"},{l:"I tell my parents everything",e:"💬"}]},
        {q:"If your parents saw your phone, you'd:",opts:[{l:"No problem at all",e:"😇"},{l:"A few awkward things",e:"😅"},{l:"Grab it back immediately",e:"😱"},{l:"Delete first",e:"🗑️"}]},
        {q:"Behavior you inherited but dislike?",opts:[{l:"Procrastination",e:"⏳"},{l:"Impatience",e:"😤"},{l:"Excessive worry",e:"😰"},{l:"I only got the good stuff",e:"😇"}]},
        {q:"If you could change one thing about your family?",opts:[{l:"Talk more openly",e:"💬"},{l:"See each other more",e:"🤗"},{l:"Fight less",e:"🕊️"},{l:"Nothing, I love it as is",e:"❤️"}]}
      ]
    }
  }
};

/* ═══ TRADUCTIONS UI ═══ */
var T = {
  fr:{
    logo:"Tu me connais ?",
    tag:"💛 Zéro inscription · 100% gratuit",
    h1:"Est-ce qu'ils te<br><em>connaissent vraiment ?</em>",
    sub:"Tu réponds sur toi. Tu envoies le lien ou le QR code. Ton pote, partenaire ou ta famille devine tes réponses. Le score ne ment pas.",
    modeLabel:"Qui joue avec toi ?",
    formatLabel:"Combien de questions ?",
    spicyLabel:"🌶 Mode Spicy",
    spicySub:"Active les questions pimentées",
    timerLabel:"⏱ Chrono par question (30s)",
    timerSub:"Désactive pour jouer sans limite de temps",
    nameLabel:"Ton prénom",
    namePh:"Ton prénom...",
    nameError:"⚠ Entre ton prénom pour continuer !",
    startBtn:"C'est parti — je réponds sur moi →",
    builderBtn:"✏️ Créer mon propre quiz",
    formats:[{n:10,l:"Court",s:"~5 min"},{n:20,l:"Moyen",s:"~10 min"},{n:30,l:"Long",s:"~15 min"}],
    intensity:[{id:"fun",l:"🌶 Fun",s:"Gênant mais drôle"},{id:"hot",l:"🔥 Hot",s:"Franchement spicy"}],
    modes:[
      {id:"friends",icon:"🤝",label:"Potes / Amis",sub:"Hobbies, vibes, habitudes..."},
      {id:"couple",icon:"💛",label:"Couple",sub:"Amour, routine, valeurs..."},
      {id:"family",icon:"👨‍👩‍👧",label:"Famille",sub:"Souvenirs, traditions..."}
    ],
    doneChip:"Tes réponses sont sauvegardées",
    shareTitle:"Envoie ça à ton ami !",
    shareSub:"Scanne le QR code ou copie le lien. Il/elle joue, vous voyez le score ensemble.",
    copyBtn:"Copier", copiedBtn:"Copié ✓",
    shareNative:"📤 Partager directement",
    backHome:"← Recommencer",
    inviteWho:"devine les réponses de",
    inviteSub:"Réponds comme tu penses qu'il/elle a répondu !",
    p2nameLabel:"Ton prénom à toi",
    p2namePh:"Ton prénom...",
    p2nameError:"⚠ Entre ton prénom !",
    startGuess:"Commencer à deviner →",
    skip:"Passer",
    nextQ:"Question suivante →",
    seeResult:"Voir le résultat →",
    correct:"✓ Bonne réponse !",
    wrong:"✗ Raté !",
    qOf:"Question",
    resultTitle:"Résultat",
    knowledgeScore:"Score de connaissance",
    correct2:"Correctes", wrong2:"Ratées", skipped2:"Passées",
    reviewTitle:"Récap des réponses",
    invertBtn:"↔ Inverser les rôles",
    restartBtn:"← Nouvelle partie",
    invertNote:"C'est maintenant au tour de",
    invertNote2:"de répondre — et toi de deviner !",
    yourNameFor:"Ton prénom (confirmé)",
    resultMsgs:[
      [0,29,"😬","Vous venez à peine de vous rencontrer ou quoi ?"],
      [30,49,"😅","Il y a encore du travail... mais c'est un bon début !"],
      [50,69,"🙂","Pas mal ! Tu commences vraiment à le/la cerner."],
      [70,84,"😄","Vous vous connaissez vraiment bien — ça se voit !"],
      [85,100,"🔥","Incroyable. Vous lisez dans les pensées de l'autre !"]
    ],
    builderTitle:"Crée ton quiz perso",
    builderSub:"Choisis parmi les questions prédéfinies ou crée les tiennes. 4 réponses par défaut, clique + pour en ajouter.",
    builderPreset:"Questions prédéfinies",
    builderCustom:"Ajouter une question personnalisée",
    builderQ:"Question",
    builderAddQ:"+ Ajouter une question",
    builderStart:"Lancer ce quiz →",
    builderBack:"← Retour",
    addOpt:"+ Ajouter une réponse",
    customQPh:"Écris ta question...",
    customOptPh:"Réponse..."
  },
  en:{
    logo:"Do you know me?",
    tag:"💛 No sign-up · 100% free",
    h1:"Do they really<br><em>know you?</em>",
    sub:"You answer questions about yourself. You share the link or QR code. Your friend, partner or family guesses your answers. The score never lies.",
    modeLabel:"Who's playing with you?",
    formatLabel:"How many questions?",
    spicyLabel:"🌶 Spicy Mode",
    spicySub:"Unlock spicy questions",
    timerLabel:"⏱ Timer per question (30s)",
    timerSub:"Disable to play with no time limit",
    nameLabel:"Your first name",
    namePh:"Your name...",
    nameError:"⚠ Please enter your name to continue!",
    startBtn:"Let's go — I answer about myself →",
    builderBtn:"✏️ Create my own quiz",
    formats:[{n:10,l:"Short",s:"~5 min"},{n:20,l:"Medium",s:"~10 min"},{n:30,l:"Long",s:"~15 min"}],
    intensity:[{id:"fun",l:"🌶 Fun",s:"Awkward but funny"},{id:"hot",l:"🔥 Hot",s:"Genuinely spicy"}],
    modes:[
      {id:"friends",icon:"🤝",label:"Friends / Mates",sub:"Hobbies, vibes, habits..."},
      {id:"couple",icon:"💛",label:"Couple",sub:"Love, routine, values..."},
      {id:"family",icon:"👨‍👩‍👧",label:"Family",sub:"Memories, traditions..."}
    ],
    doneChip:"Your answers are saved",
    shareTitle:"Send this to your friend!",
    shareSub:"Scan the QR code or copy the link. They play, you see the score together.",
    copyBtn:"Copy", copiedBtn:"Copied ✓",
    shareNative:"📤 Share directly",
    backHome:"← Start over",
    inviteWho:"guess the answers of",
    inviteSub:"Answer as you think they would have answered!",
    p2nameLabel:"Your first name",
    p2namePh:"Your name...",
    p2nameError:"⚠ Please enter your name!",
    startGuess:"Start guessing →",
    skip:"Skip",
    nextQ:"Next question →",
    seeResult:"See the result →",
    correct:"✓ Correct!",
    wrong:"✗ Wrong!",
    qOf:"Question",
    resultTitle:"Results",
    knowledgeScore:"Knowledge score",
    correct2:"Correct", wrong2:"Wrong", skipped2:"Skipped",
    reviewTitle:"Answer recap",
    invertBtn:"↔ Switch roles",
    restartBtn:"← New game",
    invertNote:"Now it's",
    invertNote2:"'s turn to answer — and yours to guess!",
    yourNameFor:"Your name (confirmed)",
    resultMsgs:[
      [0,29,"😬","Did you just meet or what?"],
      [30,49,"😅","Still some work to do... but it's a start!"],
      [50,69,"🙂","Not bad! You're starting to figure them out."],
      [70,84,"😄","You really know each other well — it shows!"],
      [85,100,"🔥","Incredible. You can literally read each other's minds!"]
    ],
    builderTitle:"Create your own quiz",
    builderSub:"Pick from preset questions or write your own. 4 answers by default, click + to add more.",
    builderPreset:"Preset questions",
    builderCustom:"Add a custom question",
    builderQ:"Question",
    builderAddQ:"+ Add a question",
    builderStart:"Launch this quiz →",
    builderBack:"← Back",
    addOpt:"+ Add an answer",
    customQPh:"Write your question...",
    customOptPh:"Answer..."
  }
};
